apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kind-wakt-config.yaml
- ../../base/wakt-pod/
patchesStrategicMerge:
- ./kind-wakt-patch.yaml
images:
- name: metrics-image
  newName: metrics-amd64
  newTag: "1.0"
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
- name: wakt-api-image
  newName: wakt-api-amd64
  newTag: "1.0"
